import Head from 'next/head'
import {BsFillMoonStarsFill, BsLinkedin, BsGithub} from 'react-icons/bs'
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import {FaCoffee} from 'react-icons/fa'
import Image from "next/image"
import ahsoka from '../public/ahsoka.jpg'
// Languages
import icon_c from '../public/tech_stack/icon-c.png'
import icon_python from '../public/tech_stack/icon-python.png'
import icon_sql from '../public/tech_stack/icon-sql.png'
import icon_js from '../public/tech_stack/icon-js.png'
import icon_html from '../public/tech_stack/icon-html.png'
import icon_css from '../public/tech_stack/icon-css.png'
import icon_r from '../public/tech_stack/icon-r.png'
// Learning
import icon_django from '../public/tech_stack/icon-django.png'
import icon_flask from '../public/tech_stack/icon-flask.png'
import icon_php from '../public/tech_stack/icon-php.png'
import icon_typescript from '../public/tech_stack/icon-typescript.png'
// Frameworks
import icon_react from '../public/tech_stack/icon-react.png'
import icon_vue from '../public/tech_stack/icon-vue.png'
import icon_electron from '../public/tech_stack/icon-electron.png'
import icon_nextjs from '../public/tech_stack/icon-nextjs.svg'
import icon_tailwind from '../public/tech_stack/icon-tailwind.svg'
// Platforms
import icon_docker from '../public/tech_stack/icon-docker.png'
import icon_git from '../public/tech_stack/icon-git.png'
import icon_nodejs from '../public/tech_stack/icon-nodejs.png'
import icon_rasp from '../public/tech_stack/icon-rasp-pi.png'
import icon_rstudio from '../public/tech_stack/icon-rstudio.png'
import icon_tableau from '../public/tech_stack/icon-tableau.png'
import icon_vscode from '../public/tech_stack/icon-vscode.png'
// React libraries
import { useState } from "react"
import { useRef } from "react"


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const home = useRef(null);
  const about = useRef(null);
  const tech = useRef(null);
  const projects = useRef(null);

  const scrollToSection = (elementRef) => {
    window.scrollTo(
      {
        top: elementRef.current.offsetTop,
        behavior: "smooth",
      }
    )
  }

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Pailin Mack Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white dark:bg-gray-900'>
        <section ref={home} className='sticky top-0 z-50'>
          {/* Navigation Bar */}
          <nav className='nav-bar'>
            <h1>
              <ul onClick={() => scrollToSection(home)} className='cursor-pointer flex items-center'>
                <li className='home-title ml-10'><FaCoffee/></li>
                <li className='home-title'>PMCodes</li>
              </ul>
            </h1>
            {/* Navigation Buttons */}
            <ul className='flex items-center'>
              <li onClick={() => scrollToSection(about)} className="nav-button">
                About
              </li>
              <li onClick={() => scrollToSection(projects)} className="nav-button">
                Projects
              </li>
              <li onClick={() => scrollToSection(tech)} className="nav-button">
                Tech Stack
              </li>
              <li className="nav-icon dark:text-white">
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}/>
              </li>
            </ul>
          </nav>
        </section>

        <section ref={home} className="section-content">
          <div className='text-center'>
            <h2 className='page-title'>Pailin Mack</h2>
            <h3 className='page-subtitle'>Developer and Coffee Enthusiast</h3>
            <p className='text-md page-body'>
              This is my digital playground, where I share what I have learned. <br/>
              On my free time, you can find me on a hiking trail or exploring the beautiful island of Oahu. <br/>
            </p>
          </div>
          <div className='icon'>
            <a href='https://github.com/psmack'><AiFillGithub /></a>
            <a href='https://www.linkedin.com/in/pailin-mack/'><AiFillLinkedin /></a>
          </div>
          <div className='mx-auto rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96'>
            <Image src={ahsoka} alt="ahoska icon"  ></Image>
          </div>               
        </section>

        <section ref={about} className="section-content">
            <div>
              <h3 className='section-title'>About</h3>
            </div>
            <div className='about'>
            <div className="about-card">
              <h3 className="about-title">Education</h3>
              <ul className="about-item">
                <li>
                  University of Maryland Global Campus
                </li>
                <li className='about-subitem'>
                  Master of Science, Cybersecurity 
                </li>
                <li className='about-subitem'>
                  2019-Present
                </li>
              </ul>
              <ul className="about-item">
                <li>
                  UMBC Training Center
                </li>
                <li className='about-subitem'>
                  Certification, Computer Programming
                </li>
                <li className='about-subitem'>
                  2019-2020
                </li>
              </ul>
              <ul className="about-item">
                <li>
                  University of California, Riverside
                </li>
                <li className='about-subitem'>
                  Bachelor of Science, Bioengineering
                </li>
                <li className='about-subitem'>
                  2007-2011
                </li>
              </ul>
            </div>

            <div className="about-card">
              <h3 className="about-title">Certification</h3>
              <ul className="about-item">
                <li className='about-subitem'>
                  Google Data Analytics Professional Certification 
                </li>
                <li className='about-subitem'>
                  CompTIA Network+ 
                </li>
              </ul>
            </div>
          </div>
        </section>

        <div ref={projects} className='pt-12'></div>
        <section className="section-content">
          <div>
            <h3 className='section-title'>Projects</h3>
          </div>
          <div className='project'>
            <div className="project-card">
              <h3 className="project-title">Python Projects</h3>
              <div className='project-repo-card' >
                <h4 className='project-repo-title'>
                  Python Mini Projects
                </h4>
                <div className="project-item">
                  Collection of simple scripts using various Python libraries.
                </div>
                <div className='icon'>
                  <a href='https://github.com/psmack/Python-Mini-Projects'><AiFillGithub /></a>
                </div>
              </div>
              <div className='project-repo-card' >
                <h4 className='project-repo-title'>
                  Youtube Music Downloader
                </h4>
                <div className="project-item">
                  Download song or album from Youtube Music using pytube library.
                </div>
                <div className='icon'>
                  <a href='https://github.com/psmack/youtube_downloader'><AiFillGithub /></a>
                </div>
              </div>
            </div>

            <div className="project-card">
              <h3 className="project-title">Data Analytics</h3>
              <div className='project-repo-card' >
                <h4 className='project-repo-title'>
                  Dashboard Panel
                </h4>
                <div className="project-item">
                  Interactive analytic visualization dashboard in Python.
                </div>
                <div className='icon'>
                  <a href='https://github.com/psmack/python-dashboard-panel'><AiFillGithub /></a>
                </div>
              </div>
            </div>

            <div className="project-card ">
              <h3 className="project-title">C Projects</h3>
              <div className='project-repo-card' >
                <h4 className='project-repo-title'>
                  Mastermind
                </h4>
                <div className="project-item">
                  Mastermind game written in C.
                </div>
                <div className='icon'>
                  <a href='https://github.com/psmack/mastermind'><AiFillGithub /></a>
                </div>
              </div>
            </div>

            <div className="project-card">
              <h3 className="project-title">Web Dev</h3>
              <div className='project-repo-card' >
                <h4 className='project-repo-title'>
                  Alliance
                </h4>
                <div className="project-item">
                Twitter clone application for the Rebel Alliance using Electron and Vue frameworks. Deployable on Web, Windows, and Andriod.
                </div>
                <div className='icon'>
                  <a href='https://github.com/psmack/alliance'><AiFillGithub /></a>
                </div>
              </div>
              <div className='project-repo-card' >
                <h4 className='project-repo-title'>
                  React Website
                </h4>
                <div className="project-item">
                  Portfolio website using React framework.
                </div>
                <div className='icon'>
                  <a href='https://github.com/psmack/react-pmcodes'><AiFillGithub /></a>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section ref={tech} className="section-content">
          <div>
            <h2 className="section-title">
                Tech Stack
            </h2>
          </div>
          <div className='tech-stack'>
            <div className="tech-stack-card">
              <h3 className="tech-stack-title">Languages</h3>
              <div className='tech-stack-item'>
                <Image src={icon_c} alt="" />
                <Image src={icon_python} alt="" />
                <Image src={icon_sql} alt="" />
                <Image src={icon_js} alt="" />
                <Image src={icon_html} alt="" />
                <Image src={icon_css} alt="" />
                <Image src={icon_r} alt="" />
              </div> 
            </div>

            <div className="tech-stack-card">
              <h3 className="tech-stack-title">Learning</h3>
              <div className='tech-stack-item'>
                <Image src={icon_django} alt="Django" />
                <Image src={icon_flask} alt="Flask" />
                <Image src={icon_php} alt="PHP" />
                <Image src={icon_typescript} alt="Typescript" />
              </div> 
            </div>

            <div className="tech-stack-card ">
              <h3 className="tech-stack-title">Frameworks</h3>
              <div className='tech-stack-item'>
                <Image src={icon_electron} alt="Electron" />
                <Image src={icon_nextjs} alt="NextJS" />
                <Image src={icon_react} alt="React" />
                <Image src={icon_tailwind} alt="Tailwind" />
                <Image src={icon_vue} alt="Vue" />
                
              </div> 
            </div>

            <div className="tech-stack-card">
              <h3 className="tech-stack-title">Platforms and Tools</h3>
              <div className='tech-stack-item'>
                <Image src={icon_docker} alt="Docker" />
                <Image src={icon_git} alt="Git" />
                <Image src={icon_nodejs} alt="NodeJS" />
                <Image src={icon_rasp} alt="Raspberry Pi" />
                <Image src={icon_rstudio} alt="R Studio" />
                <Image src={icon_tableau} alt="Tableau" />
                <Image src={icon_vscode} alt="VS Code" />
              </div> 
            </div>
          </div>
        </section>

        {/* Footer Bar */}
        <section>
          <div className='footer-bar'>
            <div className='icon'>
              <a href='https://github.com/psmack'><AiFillGithub /></a>
              <a href='https://www.linkedin.com/in/pailin-mack/'><AiFillLinkedin /></a>
            </div>
          </div>
        </section>
      </main>
    </div>
    
  )
}
