import Head from 'next/head'
import Hero from '../components/Hero';
import About from '../components/About';
import Projects from '../components/Projects';
import Techstack from '../components/Techstack';



export default function Home() {
   return (
    <div>
      <Head>
        <title>PMCodes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mug-saucer-solid.svg" />
      </Head>
      <Hero />
    </div>
  )
}
